server:
  port: 80


#没有用到数据源的情况下禁用数据源，否则与公共包中的 mybaits-plus 冲突，报错
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  application:
    name: cloud-order-feign-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
  instance:
    instance-id: orderService80
    prefer-ip-address: true
#feign:
#  httpclient:
#    #两端连接所用的时间，默认2s
#    connection-timeout: 1000
#      #建立连接并获取响应所用时间，默认为60s
#    ok-http:
#      read-timeout:


feign:
  client:
    config:
      default:
        #超时设置ms
        readTimeout: 5000
        connectTimeout: 5000

logging:
  level:
  # feign日志以什么级别监控哪个接口
    com.demo.springcloud.service.PaymentService: debug