server:
  port: 7002
#没有用到数据源的情况下禁用数据源，否则与公共包中的 mybaits-plus 冲突，报错
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
eureka:
  instance:
    hostname: eureka7002.com  #eureka服务器的实例名称
  client:
    #false表示不像eureka注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责即为维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7001.com:7001/eureka/
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000